---
application:
  name: "djzum"
  project: "Djzum"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "zumbase"
  version: "4.4"
routers:
- name: "main-djzum"
  routes:
  - application_name: "djzum"
    paths:
    - "/*"
